# Generated by Django 5.2.13 on 2026-06-11 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('emoji', models.CharField(blank=True, help_text='Icone emoji (ex 🍔)', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_nav', models.BooleanField(default=False, help_text='Afficher dans la barre du bas')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('share_token', models.CharField(blank=True, db_index=True, max_length=22, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Badge ex: Cuisine Locale / Premium', max_length=60)),
                ('bio', models.TextField(blank=True, help_text='Description / bio du restaurant')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('neighborhood', models.CharField(blank=True, help_text='Quartier ex: Bonanjo, Akwa, Bonapriso, Bali', max_length=80)),
                ('city', models.CharField(default='Douala', max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('delivery_fee', models.PositiveIntegerField(default=500, help_text='Frais livraison en FCFA')),
                ('delivery_time_min', models.PositiveSmallIntegerField(default=20)),
                ('delivery_time_max', models.PositiveSmallIntegerField(default=40)),
                ('min_order', models.PositiveIntegerField(default=0)),
                ('brand_color', models.CharField(default='#FF6B1A', max_length=9)),
                ('accent_color', models.CharField(default='#FFF1E8', max_length=9)),
                ('is_pro', models.BooleanField(default=False, help_text='Badge Pro')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='A la une')),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('categories', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('prep_time', models.PositiveSmallIntegerField(default=20, help_text='Temps de preparation (min)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='dishes/videos/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='restaurants.category')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='restaurants.menusection')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['section__order', '-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='restaurants/gallery/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['slug'], name='restaurants_slug_d8b6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['share_token'], name='restaurants_share_t_354941_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['restaurant', 'is_available'], name='restaurants_restaur_bc95d5_idx'),
        ),
    ]
