# Generated by Django 5.2.17 on 2026-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calories estimees par portion', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_note',
            field=models.CharField(blank=True, help_text='Conseil court pour aider le client a choisir', max_length=220),
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_tags',
            field=models.CharField(blank=True, help_text='Tags separes par des virgules, ex: leger, riche en proteines', max_length=160),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_diet',
            field=models.BooleanField(default=False, help_text='Plat recommande pour une alimentation equilibree'),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein_grams',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Proteines estimees par portion', null=True),
        ),
    ]
