# Generated by Django 5.2.17 on 2026-09-25 13:15

import apps.restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_dish_calories_dish_dietary_note_dish_dietary_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='carbs_grams',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Glucides estimes par portion', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat_grams',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lipides estimes par portion', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fiber_grams',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fibres estimees par portion', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closure_note',
            field=models.CharField(blank=True, help_text='Message affiche aux clients pendant la fermeture', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_temporarily_closed',
            field=models.BooleanField(default=False, help_text='Fermeture exceptionnelle : plus aucune commande acceptee'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(blank=True, default=apps.restaurants.models.default_opening_hours),
        ),
    ]
