# Generated by Django 5.2.17 on 2026-10-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_dish_carbs_grams_dish_fat_grams_dish_fiber_grams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icone dans static/icons/categories (sans .png)", max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sector__order', 'order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='min_order',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_orders_per_day',
            field=models.PositiveIntegerField(default=0, help_text='Nombre maximum de commandes acceptees par jour (0 = illimite)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.sector'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sector',
            field=models.ForeignKey(blank=True, help_text="Secteur d'activite", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurants.sector'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('sector', 'name'), name='unique_category_per_sector'),
        ),
    ]
