# Generated by Django 5.2.17 on 2026-10-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_sectors_orders_abandon_promo_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(blank=True, default='Suppléments', help_text='Rubrique affichee au client : Boissons, Suppléments, Sauces...', max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('price', models.PositiveIntegerField(default=0, help_text='FCFA ajoutes au plat (0 = offert)')),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurants.dish')),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
    ]
