# Generated by Django 5.2.13 on 2026-06-11 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.CharField(choices=[('moto', 'Moto'), ('bike', 'Velo'), ('car', 'Voiture'), ('foot', 'A pied')], default='moto', max_length=6)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=False, help_text='En ligne / disponible')),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('service_radius_km', models.PositiveSmallIntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('deliveries_count', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='restaurants.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
