# Generated by Django 5.2.17 on 2026-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Client (abandon)'), ('restaurant', 'Restaurant'), ('system', 'Système')], max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('picked_up', 'Récupérée'), ('on_the_way', 'En route'), ('arrived', 'Arrivée chez le client'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=14),
        ),
    ]
