# Generated by Django 5.2.13 on 2026-06-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devicepushtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicepushtoken',
            new_name='core_device_user_id_f1f762_idx',
            old_name='core_device_user_id_idx',
        ),
    ]
