# Generated by Django 5.2.13 on 2026-06-11 23:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('reach_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('total_redemptions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.PositiveBigIntegerField(default=0, help_text='CA genere (FCFA)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('percent', models.PositiveSmallIntegerField(default=10, help_text='Rabais en %')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = illimite')),
                ('uses', models.PositiveIntegerField(default=0)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='promotions.influencerprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='orders.order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.promocode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Theme de la promo ex: Black Friday', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Pourcentage (-X%)'), ('amount', 'Reduction fixe (-X FCFA)'), ('fixed_price', 'Prix promo (X FCFA)')], default='percent', max_length=12)),
                ('discount_value', models.PositiveIntegerField(help_text='% (ex 50, 75), montant FCFA, ou prix promo selon le type')),
                ('banner_color', models.CharField(default='#E53935', max_length=9)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('dishes', models.ManyToManyField(blank=True, related_name='promotions', to='restaurants.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
